"""add ticker_metadata model

Revision ID: 2f2c89fe4205
Revises: dc48921a536c
Create Date: 2026-08-31 16:41:50.140538

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2f2c89fe4205"
down_revision: str | Sequence[str] | None = "dc48921a536c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticker_metadata",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("sector", sa.String(), nullable=True),
        sa.Column("country", sa.String(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_index(
        op.f("ix_ticker_metadata_country"),
        "ticker_metadata",
        ["country"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticker_metadata_sector"),
        "ticker_metadata",
        ["sector"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ticker_metadata_ticker"),
        "ticker_metadata",
        ["ticker"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticker_metadata_ticker"), table_name="ticker_metadata")
    op.drop_index(op.f("ix_ticker_metadata_sector"), table_name="ticker_metadata")
    op.drop_index(op.f("ix_ticker_metadata_country"), table_name="ticker_metadata")
    op.drop_table("ticker_metadata")
    # ### end Alembic commands ###
