"""Add ticker prices cache table

Revision ID: b8c70aa5a36c
Revises: 2f2c89fe4205
Create Date: 2026-09-01 13:06:16.743796

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b8c70aa5a36c"
down_revision: str | Sequence[str] | None = "2f2c89fe4205"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ticker_prices",
        sa.Column("ticker", sa.String(), nullable=False),
        sa.Column("price", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("ticker"),
    )
    op.create_index(
        op.f("ix_ticker_prices_ticker"), "ticker_prices", ["ticker"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ticker_prices_ticker"), table_name="ticker_prices")
    op.drop_table("ticker_prices")
    # ### end Alembic commands ###
