"""Add portfolio model and relation

Revision ID: dc48921a536c
Revises: da98043cedc9
Create Date: 2026-08-21 15:36:05.382630

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlmodel.sql.sqltypes import AutoString

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "dc48921a536c"
down_revision: str | Sequence[str] | None = "da98043cedc9"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("email", AutoString(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("is_superuser", sa.Boolean(), nullable=False),
        sa.Column("full_name", AutoString(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hashed_password", AutoString(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.create_table(
        "portfolio",
        sa.Column("name", AutoString(), nullable=False),
        sa.Column("broker", AutoString(), nullable=False),
        sa.Column("description", AutoString(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_portfolio_broker"), "portfolio", ["broker"], unique=False)
    op.create_index(op.f("ix_portfolio_name"), "portfolio", ["name"], unique=False)
    op.create_table(
        "position",
        sa.Column("asset_name", AutoString(), nullable=False),
        sa.Column("ticker", AutoString(), nullable=False),
        sa.Column("isin", AutoString(), nullable=True),
        sa.Column("currency", AutoString(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("unit_cost", sa.Numeric(precision=18, scale=8), nullable=True),
        sa.Column("acquisition_date", sa.Date(), nullable=False),
        sa.Column("portfolio_id", sa.Integer(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["portfolio_id"],
            ["portfolio.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("position")
    op.drop_index(op.f("ix_portfolio_name"), table_name="portfolio")
    op.drop_index(op.f("ix_portfolio_broker"), table_name="portfolio")
    op.drop_table("portfolio")
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.drop_table("user")
    # ### end Alembic commands ###
